services:
  postgres:
    image: postgres:17.5
    volumes:
      - .psqlrc:/root/.psqlrc:ro
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/app
    environment:
      DATABASE_HOST: postgres
    ports:
      - '3000:3000'

volumes:
  postgres:
  redis:
