name: kittengrid
on: pull_request
jobs:
  kittengrid:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # install your project dependencies here

      - name: Kittengrid
        uses: kittengrid/action
        env:
          KITTENGRID_API_KEY: ${{ secrets.KITTENGRID_API_KEY }}
